version: '2'
services:
  zookeeper:
    image: sumglobal/rpi-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: sumglobal/rpi-kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.1.203
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
